import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import { RootProvider } from "./rootProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

// REMOVED "export const metadata = {}" to fix the conflict

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: process.env.NEXT_PUBLIC_PROJECT_NAME,
    description: "Generated by `create-onchain`, a Next.js template for OnchainKit",
    other: {
      'fc:miniapp': JSON.stringify({
        version: 'next',
        imageUrl: 'https://your-app.com/embed-image',
        button: {
          title: `Get Started`,
          action: {
            type: 'launch_miniapp',
            name: 'Credibles',
            url: 'https://work-proof-seven.vercel.app/',
            splashImageUrl: 'https://work-proof-seven.vercel.app/sphere.svg',
            splashBackgroundColor: '#000000',
          },
        },
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}